### ISSUE TITLE
Settings.py on Mac

### ISSUE THREAD

**Issue by stevezau** [vacoj/MINDBODY-Django#2]
Hi,

Trying to set this up on my mac but getting "django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details."

I suspect this is something to do with https://github.com/vacoj/MINDBODY-Django/blob/master/mboapi_djangodemo/settings.py#L95 not setting the database up correctly..

**Comment by vacovsky** [comment]
It's because the settings file has a hard-coded value for my dev VM.  Just change that value to your own host name and you likely won't get that error.  That was just to make it easy for me to deploy the application into Heroku without needing to constantly adjust the configuration file (I could have done this many other ways, but this one was expedient).

```
# different settings based on system name
if (socket.gethostname() != '**YOUR HOSTNAME HERE**'):
    DATABASES['default'] = dj_database_url.config()
    print(socket.gethostname())
    DEBUG = False
    STATIC_ROOT = 'staticfiles'
    STATIC_URL = '/static/'
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

else:
    LOCAL_PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(LOCAL_PROJECT_DIR, 'testingdb.db'),
        }
    }
    STATIC_ROOT = 'staticfiles'
    STATIC_URL = '/static/'
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
```
